HHS/TANF-app

README.md

Update documentation to test workflow

---

upload/templates/about.html

demo change to about page

---

ftanf.py

Don't key off of section3 data, instead just key off of section, so that we can parse any section data.

fix ftanf.py so that it is more general

---

docs/Sprint Review/Sprint 5.md

- Adds a Sprint Review folder in docs and Sprint 5 summary.

Sprint 5 summary.md

---

.circleci/config.yml

+ https://github.com/raft-tech/TANF-app/issues/285.
+ This PR copies over changes from https://github.com/raft-tech/TANF-app/pull/360/files to see if they get our frontend tests to go green on the HHS repository.

Disable Docker Layer Caching

---

docs/Sprint Review/Sprint 6 Summary.md

Sprint 6 summary
Add Sprint 6 summary

Create Sprint 6 Summary.md

---

.github/ISSUE_TEMPLATE/design-issue-template.md
.github/ISSUE_TEMPLATE/research-issue-template-.md

- Offboards @cmajel from design/research review flow
- Introduces a few incidental whitespace changes
This PR is a part of: https://github.com/raft-tech/TANF-app/issues/297.

Offboard @cmajel from design/research review flow 😢

---

docs/Sprint Review/Sprint 7 Summary.md

Create Sprint 7 Summary.md

---

docs/Sprint Review/Sprint 8 Summary.md

Create Sprint 8 Summary.md

---

docs/Sprint Review/Sprint 8 Summary.md

Update Sprint 8 Summary.md

---

docs/How-We-Work/team-charter/our-workflow.md
docs/Technical-Documentation/Configuration-Management-Plan.md

Draft Configuration Management Plan; still needs input from dev team and Product Owner. 
https://github.com/HHS/TANF-app/blob/ars/cmp/docs/Technical-Documentation/Configuration-Management-Plan.md
Note that this diff includes a large number of whitespace changes, you may want to use this link for review (hides whitespace change in the file diff): https://github.com/HHS/TANF-app/pull/96/files?w=1
https://github.com/raft-tech/TANF-app/issues/392
... the Product Owner has reviewed and approved this documentation.

Add Configuration Management Plan

---

docs/Sprint-Review/Sprint 9.md

Create Sprint 9.md

---

docs/Sprint-Review/Sprint 10 Summary.md

Adds Sprint 10 Summary
- OpenAPI  
- Readme

Create Sprint 10 Summary.md

---

docs/Sprint-Review/Sprint 11 Summary.md

Add sprint 11 summary 
- OpenAPI  
- Readme

Create Sprint 11 Summary.md

---

docs/Architecture Decision Record/001 ADR template.md

Adding template for recoding architectural decisions
- OpenAPI  
- Readme

Create 001 ADR template.md

---

docs/User-Research/Overview of Research Activities.md

Update overview with the round 3 research activities
- OpenAPI  
- Readme

Update Overview of Research Activities.md

---

docs/Architecture Decision Record/002 Application architecture.md

Adding application architecture decision
- OpenAPI  
- Readme

Create 002 Application architecture.md

---

docs/Architecture Decision Record/003 Application hosting.md

*List expected changes*
add ADR on hosting TDP on Cloud.gov
- OpenAPI  
- Readme

Create 003 Application hosting.md

---

docs/User-Research/STT attribute guide.md

Add STT attribute guide to user research
- OpenAPI  
- Readme

Create STT attribute guide.md

---

docs/Security-Compliance/records-management.md

Preview: https://github.com/HHS/TANF-app/blob/bh-docs-records-management/docs/Security-Compliance/records-management.md

Add records management doc

---

docs/Background/Project-Impact.md

Preview: https://github.com/HHS/TANF-app/blob/bh-docs-assumptions/docs/Background/Project-Impact.md

Add assumptions to project impact doc

---

docs/Technical-Documentation/how-government-will-test-a11y.md

Preview: https://github.com/HHS/TANF-app/blob/bh-a11y-doc-updates/docs/Technical-Documentation/how-government-will-test-a11y.md

Small tweaks to a11y doc

---

docs/Sprint-Review/Sprint 1 Summary.md

Create Sprint 1 summary
- OpenAPI  
- Readme

Create Sprint 1 Summary.md

---

docs/Sprint-Review/Sprint 2 Summary.md

Add Sprint 2 Summary
- OpenAPI  
- Readme

Create Sprint 2 Summary.md

---

docs/Sprint 3 Summary.md

Add sprint 3 summary
- OpenAPI  
- Readme

Create Sprint 3 Summary.md

---

docs/Sprint-Review/Sprint 4 Summary.md

Add sprint 4 summary
- OpenAPI  
- Readme

Create Sprint 4 Summary.md

---

docs/Sprint-Review/Sprint 12 Summary

*Add a sprint 12 summary*
- OpenAPI  
- Readme

Create Sprint 12 Summary

---

docs/Sprint-Review/Sprint-12-Summary.md

*changing to .md, minor text change*

Update and rename Sprint 12 Summary to Sprint-12-Summary.md

---

docs/Architecture Decision Record/006-deployment-flow.md
docs/Architecture Decision Record/008-deployment-flow.md

+ Adds a proposed Deployment Flow for the system as an Architectural Decision Record (ADR)
+ Prompted by investigation into current Cloud.gov Spaces when starting work on https://github.com/raft-tech/TANF-app/issues/521.
[Preview link -- proposed 008-deployment-flow.md](https://github.com/HHS/TANF-app/blob/ars/adr-deployment-flow/docs/Architecture%20Decision%20Record/008-deployment-flow.md).
+ [x] Development team including vendor Tech Lead has weighed in and approved
+ [ ] Product Owner has asked questions, weighed in and approved

Proposed ADR: Deployment Flow

---

docs/Design/Design-Guide.md

Updates to Design Guide document to begin style guide work as per [#505](https://github.com/raft-tech/TANF-app/issues/505)

Update Design Guide

---

docs/README.md

Updated New TDRS to TANF Data Portal.
p.s. first pairing session with Alex S 👍🏾

Use TDP terminology

---

docs/User-Research/2020, Winter - User Flow Validation/ST Workshop Facilitation Guide.md

Add facilitation guide used to conduct round 4 research workshop with states and territories.
- OpenAPI  
- Readme

Create ST Workshop Facilitation Guide.md

---

tdrs-backend/Pipfile.lock

https://github.com/raft-tech/TANF-app/releases/tag/v2.2.3

v2.2.3: Patch update for dependency -- Pipeline-breaking change

---

.circleci/config.yml
tdrs-backend/Pipfile.lock

Resolves issue with dependency that is preventing backend build. This is needed to owasp nightly scans. More details here: https://github.com/raft-tech/TANF-app/releases/tag/v2.2.3

v2.2.3 to master

---

tdrs-frontend/manifest.buildpack.yml

Hotfix to account for large file uploads

mem increase for nginx

---

commands.sh
tdrs-backend/apt.yml

Creates a version of #2744 for production
* [Updating apt repo for postgres](https://github.com/raft-tech/TANF-app/pull/2744)

Update apt repo for postgres

---

.circleci/deployment/jobs.yml
.circleci/deployment/workflows.yml

This is only to test the new deploy pipeline changes against the staging env.
All that should happen is the pipeline deploys to staging  kick off and run fine.
_List the steps to test the PR_
These steps are generic, please adjust as necessary.
```
cd tdrs-frontend && docker-compose -f docker-compose.yml -f docker-compose.local.yml up -d
cd tdrs-backend && docker-compose -f docker-compose.yml -f docker-compose.local.yml up -d 
```
1. Open http://localhost:3000/ and sign in.
1. Proceed with functional tests as described herein.
1. Test steps should be captured in the demo GIF(s) and/or screenshots below.
> *Demo GIF(s) and screenshots for testing procedure*
_More details on how deliverables herein are assessed included [here](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Wo …

Test new deploy

---

.circleci/config.yml

testing deploy on HHS side.
_List the steps to test the PR_
These steps are generic, please adjust as necessary.
```
cd tdrs-frontend && docker-compose -f docker-compose.yml -f docker-compose.local.yml up -d
cd tdrs-backend && docker-compose -f docker-compose.yml -f docker-compose.local.yml up -d 
```
1. Open http://localhost:3000/ and sign in.
1. Proceed with functional tests as described herein.
1. Test steps should be captured in the demo GIF(s) and/or screenshots below.
> *Demo GIF(s) and screenshots for testing procedure*
_More details on how deliverables herein are assessed included [here](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverables)._
Checklist of ACs:
+ [ ] [**_insert ACs here_**]
+ [ ] **`lfrohlich`** …

have circleci track hhs-dev-devops branch

---

.circleci/deployment/workflows.yml

testing deploy on HHS side.
_List the steps to test the PR_
These steps are generic, please adjust as necessary.
```
cd tdrs-frontend && docker-compose -f docker-compose.yml -f docker-compose.local.yml up -d
cd tdrs-backend && docker-compose -f docker-compose.yml -f docker-compose.local.yml up -d 
```
1. Open http://localhost:3000/ and sign in.
1. Proceed with functional tests as described herein.
1. Test steps should be captured in the demo GIF(s) and/or screenshots below.
> *Demo GIF(s) and screenshots for testing procedure*
_More details on how deliverables herein are assessed included [here](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverables)._
Checklist of ACs:
+ [ ] [**_insert ACs here_**]
+ [ ] **`lfrohlich`** …

removing clamav step for now since it only happens in prod anyway

---

tdrs-frontend/src/components/Header/Header.jsx
tdrs-frontend/src/components/SiteMap/SiteMap.jsx
tdrs-frontend/src/selectors/auth.js

Patch release to merge latest DIGIT permissions. The Grafana based permissions already exist in all environments

Patch Release v4.1.1

---

tdrs-backend/tdpservice/users/models.py
tdrs-frontend/src/components/Reports/FRAReports.jsx

This patch release contains two fixes:
- Disables the file download for regional staff users
- Fixes a permissions check that disallows users with the user `has_fra_access` from submitting FRA data

Patch Release v4.1.2
